# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CBf2F1cAlYWvXesbN4fj_FCfCmw_QaOj
"""

lists = [10,20,30,'surendra',3.4] 
lists[4]

lists.append('king')

lists

lists.remove('king')

lists
print(len(lists))

lists.insert(1,"nani")
lists

lists.pop(4)
lists

lists.pop() #Remove the last item from the list
lists

print(lists)