# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11XX3d7SdBvzxSgFNcLuKjP3JCEpXM-nh
"""

dicts = {'Name':'Surendra','Age': 20,'interest':"development",'role':'Student'}
dicts
dicts['Name']

print(len(dicts))
type(dicts) # type of data

dicts["college"] ="TECH" # adding new item into dict
dicts
dicts.update({"college":"TEC"}) #UPDATE the item coolege name
dicts

dicts